### PR TITLE
Added Domain Models

### PR DESCRIPTION
**Pull request by alexsoto24**
Added the domain models, let me know if you guys want me to make changes, add new classes or add any more methods to any of the existing classes.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
This looks good.

**Review by dannydjg16 — APPROVED** [review]
These classes look great

**Review by dannydjg16 — CHANGES_REQUESTED** [review]
I actually just realized it looks like there is the connection string in the appsettings file

**Review by dannydjg16 — APPROVED** [review]
Nice job

**Pull request merged**
